env:
  browser: true
  es2020: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@blueprintjs/recommended"
  - prettier
  - prettier/@typescript-eslint
  - prettier/react
  - plugin:prettier/recommended
  - plugin:react-hooks/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - prettier
rules:
  indent: ["error", 2]
  linebreak-style: ["error", "unix"]
  quotes: ["error", "double"]
  semi: ["error", "always"]
  react/prop-types: [0]
  no-unused-vars: ["warn", { argsIgnorePattern: "^_" }]
  "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }]
